# Generated by Django 2.1.1 on 2018-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('link', models.CharField(max_length=2000, verbose_name='Link')),
                ('image', models.CharField(max_length=200, verbose_name='Image')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('published', models.DateTimeField(verbose_name='Published Date')),
                ('price', models.CharField(max_length=30, verbose_name='Price')),
                ('sort', models.CharField(max_length=15, verbose_name='Sort')),
                ('urli', models.CharField(max_length=250, verbose_name='Urli')),
            ],
        ),
    ]
